Add an initial support for electro-nuclear process and model  (#2170)
* Add support for the electro-nuclear process/model

* Add initial skeleton for the electro-nuclear interactor

* Add initial tests for electro-nuclear cross section calculations

* Add electro-nuclear cross section calculation

* Add electro-nuclear data, ElectroNuclearData

* Add support for the electro-nuclear process/model

* Add ElectroNuclearProcess test

* Fixed undefined reference to calc_electro_nuclear_xs

* Replace test points near the lower-bound region

* Remove version dependent test points

* Add missing comment separator line

* Remove redundant CELER_EXPECT check

* Move cross-section tabulation documentation to the method description

* Fix a typo: change photon to particle

---------

Co-authored-by: Soon Yung Jun <soon.yung.jun@cern.ch>