Support CUDA 12.9 and NVCC with cxxstd=20 (#1787)
* Update wildstyle env and default spack to C++20 due to covfie

* Default build script to be verbose for first configure

* Add requirement for covfie usage, and fix read-only nature of CUDA host compiler

* Add pre-commit to spack env

* Work around NVCC parsing bug

```
/home/s3j/Code/celeritas/src/orange/detail/BIHIntersectingVolFinder.hh(259): error: expected a ">"
                  && intersection.distance < min_intersection.distance)
                                                                      ^
```

* Fix use of host-device for bool

* Add missing includes trying to get cherenkov generator working

* IWYU

* Work around nvcc crash

```
nvcc error   : 'cudafe++' died due to signal 11 (Invalid memory reference)
nvcc error   : 'cudafe++' core dumped
```

* Fix pedantic warning

* Fix GCC 8.5 warning

* Update wildstyle presets

* Fix buggy operator== in Range on nvcc with cxxstd=20

* Update CI tests to work with G4 11.3.2